/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List past analyses (newest first) */
        get: operations["list_analyses_api_v1_analyses_get"];
        put?: never;
        /** Start an analysis of a patch */
        post: operations["create_analysis_api_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an analysis and its report */
        get: operations["get_analysis_api_v1_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        /** Delete an analysis */
        delete: operations["delete_analysis_api_v1_analyses__analysis_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream analysis progress (server-sent events) */
        get: operations["stream_events_api_v1_analyses__analysis_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export a completed report as JSON, Markdown, or SARIF */
        get: operations["export_analysis_api_v1_analyses__analysis_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest offline evaluation report (if bundled) */
        get: operations["evaluation_api_v1_evaluation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities, limits, and AI provider status */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog of every rule ChangeGuard can report */
        get: operations["rules_api_v1_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List built-in sample scenarios */
        get: operations["list_samples_api_v1_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/samples/{sample_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a sample scenario, including its patch */
        get: operations["sample_detail_api_v1_samples__sample_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/samples/{sample_id}/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyse a sample scenario */
        post: operations["analyse_sample_api_v1_samples__sample_id__analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AIAnalysis
         * @description Model-generated analysis attached to a finding. Never replaces deterministic fields.
         */
        AIAnalysis: {
            confidence: components["schemas"]["Confidence"];
            /** Evidence Ids */
            evidence_ids: string[];
            /** Explanation */
            explanation: string;
            /** Failure Scenario */
            failure_scenario: string;
            /** Model */
            model: string;
            suggested_test: components["schemas"]["SuggestedTest"];
            /**
             * Support
             * @description Share of self-consistency samples that agreed (when sampling > 1).
             */
            support: number | null;
            /** Uncertainty */
            uncertainty: string;
            /**
             * Verified
             * @default true
             */
            verified: boolean;
        };
        /** AIStatus */
        AIStatus: {
            /** Configured */
            configured: boolean;
            /** Detail */
            detail: string | null;
            /** Model */
            model: string | null;
            /** Model Available */
            model_available: boolean | null;
            /** Provider */
            provider: string;
            /** Reachable */
            reachable: boolean | null;
            /**
             * Samples
             * @default 1
             */
            samples: number;
        };
        /** AISummary */
        AISummary: {
            /** Calls */
            calls: components["schemas"]["ModelCallTrace"][];
            /** Context Chars */
            context_chars: number | null;
            /**
             * Context Truncated
             * @default false
             */
            context_truncated: boolean;
            /** Model */
            model: string | null;
            /** Note */
            note: string | null;
            /** Overall Assessment */
            overall_assessment: string | null;
            /** Prompt Id */
            prompt_id: string | null;
            /** Prompt Sha256 */
            prompt_sha256: string | null;
            /** Prompt Version */
            prompt_version: string | null;
            /** Provider */
            provider: string | null;
            /**
             * Samples
             * @default 1
             */
            samples: number;
            /**
             * Status
             * @enum {string}
             */
            status: "disabled" | "completed" | "failed" | "skipped";
            verification: components["schemas"]["AIVerification"] | null;
        };
        /** AIVerification */
        AIVerification: {
            /**
             * Claims Accepted
             * @default 0
             */
            claims_accepted: number;
            /**
             * Claims Rejected
             * @default 0
             */
            claims_rejected: number;
            /**
             * Claims Total
             * @default 0
             */
            claims_total: number;
            /** Rejected */
            rejected: components["schemas"]["RejectedClaim"][];
        };
        /** AnalysisDetail */
        AnalysisDetail: {
            /**
             * Ai Requested
             * @default false
             */
            ai_requested: boolean;
            /** Created At */
            created_at: string;
            /** Duration Ms */
            duration_ms: number | null;
            error: components["schemas"]["AnalysisError"] | null;
            /** Id */
            id: string;
            links: components["schemas"]["AnalysisLinks"];
            report: components["schemas"]["Report"] | null;
            /** Sample Id */
            sample_id: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "upload" | "paste" | "sample" | "cli";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed";
            summary: components["schemas"]["HistorySummary"] | null;
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
        };
        /** AnalysisError */
        AnalysisError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** AnalysisLinks */
        AnalysisLinks: {
            /** Events */
            events: string;
            /** Export Json */
            export_json: string;
            /** Export Markdown */
            export_markdown: string;
            /** Export Sarif */
            export_sarif: string;
            /** Self */
            self: string;
        };
        /** AnalysisList */
        AnalysisList: {
            /** Items */
            items: components["schemas"]["AnalysisSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** AnalysisSummary */
        AnalysisSummary: {
            /**
             * Ai Requested
             * @default false
             */
            ai_requested: boolean;
            /** Created At */
            created_at: string;
            /** Duration Ms */
            duration_ms: number | null;
            error: components["schemas"]["AnalysisError"] | null;
            /** Id */
            id: string;
            links: components["schemas"]["AnalysisLinks"];
            /** Sample Id */
            sample_id: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "upload" | "paste" | "sample" | "cli";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed";
            summary: components["schemas"]["HistorySummary"] | null;
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
        };
        /** Body_create_analysis_api_v1_analyses_post */
        Body_create_analysis_api_v1_analyses_post: {
            /**
             * Ai
             * @description Run optional AI synthesis (requires a configured provider)
             * @default false
             */
            ai: boolean;
            /**
             * Coverage
             * @description Optional coverage report (Cobertura XML, LCOV, coverage.py JSON)
             */
            coverage?: string | null;
            /**
             * Patch
             * @description Unified diff / git patch file
             */
            patch?: string | null;
            /**
             * Patch Text
             * @description Patch pasted as text (alternative to `patch`)
             */
            patch_text?: string | null;
            /**
             * Repository
             * @description Optional snapshot of the base revision (.zip / .tar.gz)
             */
            repository?: string | null;
            /** Title */
            title?: string | null;
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "breaking_change" | "behavior_change" | "logic_change" | "correctness" | "syntax_error" | "security" | "secret_exposure" | "error_handling" | "concurrency" | "test_gap" | "coverage_gap" | "test_integrity" | "data_migration" | "dependency" | "complexity" | "debug_artifact" | "configuration" | "type_safety" | "prompt_injection";
        /**
         * Confidence
         * @enum {string}
         */
        Confidence: "high" | "medium" | "low";
        /** Evidence */
        Evidence: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** End Line */
            end_line: number | null;
            /**
             * Excerpt
             * @description Verbatim source excerpt (untrusted content).
             */
            excerpt: string | null;
            /** Excerpt Start Line */
            excerpt_start_line: number | null;
            /** File */
            file: string | null;
            /** Highlight Lines */
            highlight_lines: number[];
            /**
             * Id
             * @description Stable identifier within a report, e.g. 'E3'.
             */
            id: string;
            /** Side */
            side: ("head" | "base") | null;
            /**
             * Source
             * @description What produced this evidence (diff, repository snapshot, ruff, coverage report, ...).
             */
            source: string;
            /** Start Line */
            start_line: number | null;
            /** Title */
            title: string;
            type: components["schemas"]["EvidenceType"];
        };
        /**
         * EvidenceType
         * @enum {string}
         */
        EvidenceType: "diff_hunk" | "code" | "call_site" | "signature_change" | "static_diagnostic" | "pattern_match" | "test_reference" | "coverage" | "metric" | "dependency" | "symbol_reference";
        /** Explanation */
        Explanation: {
            /** Evidence Ids */
            evidence_ids: string[];
            /** Model */
            model: string | null;
            /**
             * Source
             * @default template
             * @enum {string}
             */
            source: "template" | "ai";
            /** Text */
            text: string;
            /** Uncertainty */
            uncertainty: string | null;
        };
        /** FileCoverageSummary */
        FileCoverageSummary: {
            /** Covered */
            covered: number;
            /** Executable */
            executable: number;
            /** Uncovered Lines */
            uncovered_lines: number[];
        };
        /** FileSummary */
        FileSummary: {
            /** Additions */
            additions: number;
            /** Changed Symbols */
            changed_symbols: string[];
            coverage: components["schemas"]["FileCoverageSummary"] | null;
            /** Deletions */
            deletions: number;
            /** Full Context */
            full_context: boolean;
            /** Hunks */
            hunks: components["schemas"]["HunkModel"][];
            /**
             * Is Binary
             * @default false
             */
            is_binary: boolean;
            /** Is Test */
            is_test: boolean;
            /** Language */
            language: string;
            /** Old Path */
            old_path: string | null;
            /** Path */
            path: string;
            /**
             * Status
             * @enum {string}
             */
            status: "added" | "deleted" | "modified" | "renamed" | "copied";
            /** Structural Support */
            structural_support: boolean;
        };
        /** Finding */
        Finding: {
            ai_analysis: components["schemas"]["AIAnalysis"] | null;
            category: components["schemas"]["Category"];
            confidence: components["schemas"]["Confidence"];
            /** Corroborated By */
            corroborated_by: string[];
            /** Description */
            description: string;
            /** Evidence Ids */
            evidence_ids: string[];
            explanation: components["schemas"]["Explanation"];
            /** Failure Scenario */
            failure_scenario: string;
            /** Id */
            id: string;
            kind: components["schemas"]["FindingKind"];
            location: components["schemas"]["Location"];
            /** Related Symbols */
            related_symbols: string[];
            /** Rule Id */
            rule_id: string;
            severity: components["schemas"]["Severity"];
            suggested_test: components["schemas"]["SuggestedTest"];
            /** Tags */
            tags: string[];
            /** Title */
            title: string;
        };
        /**
         * FindingKind
         * @enum {string}
         */
        FindingKind: "deterministic" | "heuristic" | "ai";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** HistorySummary */
        HistorySummary: {
            /**
             * Additions
             * @default 0
             */
            additions: number;
            /** Ai Status */
            ai_status: string | null;
            /** By Kind */
            by_kind: {
                [key: string]: number;
            };
            /** By Severity */
            by_severity: {
                [key: string]: number;
            };
            /**
             * Deletions
             * @default 0
             */
            deletions: number;
            /**
             * Files Changed
             * @default 0
             */
            files_changed: number;
            /**
             * Findings Total
             * @default 0
             */
            findings_total: number;
            /** Languages */
            languages: string[];
            /** Mode */
            mode: string | null;
            /** Patch Coverage */
            patch_coverage: number | null;
            /** Review Priority */
            review_priority: string | null;
        };
        /** HunkLine */
        HunkLine: {
            /** Content */
            content: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "context" | "add" | "del";
            /** New */
            new: number | null;
            /** Old */
            old: number | null;
        };
        /** HunkModel */
        HunkModel: {
            /** Header */
            header: string;
            /** Lines */
            lines: components["schemas"]["HunkLine"][];
            /** New Count */
            new_count: number;
            /** New Start */
            new_start: number;
            /** Old Count */
            old_count: number;
            /** Old Start */
            old_start: number;
            /**
             * Section
             * @default
             */
            section: string;
        };
        /** InputSummary */
        InputSummary: {
            /** Coverage Format */
            coverage_format: string | null;
            /** Has Coverage */
            has_coverage: boolean;
            /** Has Snapshot */
            has_snapshot: boolean;
            /**
             * Mode
             * @enum {string}
             */
            mode: "full_context" | "diff_only";
            /** Patch Format */
            patch_format: string;
            /** Patch Sha256 */
            patch_sha256: string;
            /** Snapshot */
            snapshot: {
                [key: string]: unknown;
            } | null;
            /** Subject */
            subject: string | null;
        };
        /** Location */
        Location: {
            /** End Line */
            end_line: number | null;
            /** File */
            file: string;
            /**
             * Side
             * @default head
             * @enum {string}
             */
            side: "head" | "base";
            /** Start Line */
            start_line: number | null;
            /** Symbol */
            symbol: string | null;
        };
        /** Meta */
        Meta: {
            ai: components["schemas"]["AIStatus"];
            /** Auth Required */
            auth_required: boolean;
            /** Input Formats */
            input_formats: {
                [key: string]: string[];
            };
            /** Limits */
            limits: {
                [key: string]: number;
            };
            /** Line Level File Types */
            line_level_file_types: string[];
            /**
             * Name
             * @default ChangeGuard
             */
            name: string;
            /** Report Schema Version */
            report_schema_version: string;
            /** Ruleset Version */
            ruleset_version: string;
            /** Stages */
            stages: components["schemas"]["StageInfo"][];
            /** Structural Languages */
            structural_languages: string[];
            /** Version */
            version: string;
        };
        /** ModelCallTrace */
        ModelCallTrace: {
            /**
             * Attempts
             * @default 1
             */
            attempts: number;
            /**
             * Cache Hit
             * @default false
             */
            cache_hit: boolean;
            /** Call Id */
            call_id: string;
            /** Error */
            error: string | null;
            /** Input Tokens */
            input_tokens: number | null;
            /** Latency Ms */
            latency_ms: number;
            /** Model */
            model: string;
            /** Output Tokens */
            output_tokens: number | null;
            /** Prompt Id */
            prompt_id: string;
            /** Prompt Sha256 */
            prompt_sha256: string;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /** Request Sha256 */
            request_sha256: string;
            /** Started At */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "invalid_output" | "timeout" | "error";
        };
        /** PatchCoverage */
        PatchCoverage: {
            /** Covered */
            covered: number;
            /** Executable */
            executable: number;
            /** Percent */
            percent: number | null;
        };
        /**
         * Problem
         * @description RFC 9457 problem details.
         */
        Problem: {
            /** Code */
            code: string;
            /** Detail */
            detail: string;
            /** Errors */
            errors: {
                [key: string]: unknown;
            }[] | null;
            /** Request Id */
            request_id: string | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @default about:blank
             */
            type: string;
        };
        /** RejectedClaim */
        RejectedClaim: {
            /** Reasons */
            reasons: string[];
            /** Summary */
            summary: string;
            /**
             * Target
             * @description What the claim was attached to (finding id or 'additional_risk').
             */
            target: string;
        };
        /** Report */
        Report: {
            ai: components["schemas"]["AISummary"];
            /** Analysis Id */
            analysis_id: string;
            /** Created At */
            created_at: string;
            /** Engine Version */
            engine_version: string;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Files */
            files: components["schemas"]["FileSummary"][];
            /** Findings */
            findings: components["schemas"]["Finding"][];
            input: components["schemas"]["InputSummary"];
            /** Limitations */
            limitations: string[];
            /** Pipeline */
            pipeline: components["schemas"]["StageResult"][];
            /** Ruleset Version */
            ruleset_version: string;
            /** Schema Version */
            schema_version: string;
            summary: components["schemas"]["Summary"];
            /** Symbols */
            symbols: components["schemas"]["SymbolChangeSummary"][];
            /** Title */
            title: string;
            /** Warnings */
            warnings: string[];
        };
        /** ReviewPriority */
        ReviewPriority: {
            /**
             * Level
             * @enum {string}
             */
            level: "block" | "high" | "elevated" | "routine";
            /** Rationale */
            rationale: string;
            /** Triggered By */
            triggered_by: string[];
        };
        /** RuleInfo */
        RuleInfo: {
            category: components["schemas"]["Category"];
            default_severity: components["schemas"]["Severity"];
            /** Id */
            id: string;
            kind: components["schemas"]["FindingKind"];
            /** Languages */
            languages: string[];
            /** Rationale */
            rationale: string;
            /**
             * Source
             * @enum {string}
             */
            source: "changeguard" | "ruff";
            /** Title */
            title: string;
        };
        /** SampleDetail */
        SampleDetail: {
            /** Coverage Filename */
            coverage_filename: string | null;
            /** Description */
            description: string;
            /** Files */
            files: string[];
            /** Has Coverage */
            has_coverage: boolean;
            /** Highlights */
            highlights: string[];
            /** Id */
            id: string;
            /** Language */
            language: string;
            /** Patch */
            patch: string;
            /**
             * Synthetic
             * @default true
             */
            synthetic: boolean;
            /** Tagline */
            tagline: string;
            /** Tags */
            tags: string[];
            /** Title */
            title: string;
        };
        /** SampleSummary */
        SampleSummary: {
            /** Description */
            description: string;
            /** Files */
            files: string[];
            /** Has Coverage */
            has_coverage: boolean;
            /** Highlights */
            highlights: string[];
            /** Id */
            id: string;
            /** Language */
            language: string;
            /**
             * Synthetic
             * @default true
             */
            synthetic: boolean;
            /** Tagline */
            tagline: string;
            /** Tags */
            tags: string[];
            /** Title */
            title: string;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "critical" | "high" | "medium" | "low" | "info";
        /** StageInfo */
        StageInfo: {
            /** Label */
            label: string;
            /** Name */
            name: string;
        };
        /** StageResult */
        StageResult: {
            /** Duration Ms */
            duration_ms: number;
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Notes */
            notes: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "skipped" | "warning" | "failed";
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
        };
        /** SuggestedTest */
        SuggestedTest: {
            /** Code */
            code: string | null;
            /** Description */
            description: string;
            /**
             * Kind
             * @default unit
             * @enum {string}
             */
            kind: "unit" | "integration" | "regression" | "manual" | "static" | "review";
            /** Language */
            language: string | null;
            /**
             * Source
             * @default template
             * @enum {string}
             */
            source: "template" | "ai";
        };
        /** Summary */
        Summary: {
            /** Additions */
            additions: number;
            /** Breaking Symbols */
            breaking_symbols: number;
            /** By Category */
            by_category: {
                [key: string]: number;
            };
            /** By Kind */
            by_kind: {
                [key: string]: number;
            };
            /** By Severity */
            by_severity: {
                [key: string]: number;
            };
            /** Changed Symbols */
            changed_symbols: number;
            /** Deletions */
            deletions: number;
            /** Files Changed */
            files_changed: number;
            /** Findings Total */
            findings_total: number;
            /** Languages */
            languages: string[];
            patch_coverage: components["schemas"]["PatchCoverage"] | null;
            review_priority: components["schemas"]["ReviewPriority"];
            /** Symbols With Tests */
            symbols_with_tests: number;
            /** Testable Symbols */
            testable_symbols: number;
        };
        /** SymbolChangeSummary */
        SymbolChangeSummary: {
            /**
             * Approximate
             * @default false
             */
            approximate: boolean;
            /**
             * Breaking
             * @default false
             */
            breaking: boolean;
            /**
             * Call Site Files
             * @default 0
             */
            call_site_files: number;
            /**
             * Call Sites
             * @default 0
             */
            call_sites: number;
            /**
             * Change
             * @enum {string}
             */
            change: "added" | "removed" | "modified" | "renamed";
            /** Complexity After */
            complexity_after: number | null;
            /** Complexity Before */
            complexity_before: number | null;
            /** End Line */
            end_line: number | null;
            /** File */
            file: string;
            /**
             * Incompatible Call Sites
             * @default 0
             */
            incompatible_call_sites: number;
            /** Kind */
            kind: string;
            /** Qualname */
            qualname: string;
            /**
             * Related Tests
             * @default 0
             */
            related_tests: number;
            /** Renamed From */
            renamed_from: string | null;
            /** Signature After */
            signature_after: string | null;
            /** Signature Before */
            signature_before: string | null;
            /** Start Line */
            start_line: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_analyses_api_v1_analyses_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Filter by title */
                q?: string | null;
            };
            header?: {
                /** @description Opaque workspace ID. Requests that carry one only see analyses created in it. */
                "X-ChangeGuard-Workspace"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analysis_api_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Opaque workspace ID. Requests that carry one only see analyses created in it. */
                "X-ChangeGuard-Workspace"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_analysis_api_v1_analyses_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSummary"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Analysis not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Input exceeds a size limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Unsupported input format */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Malformed input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_analysis_api_v1_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: {
                /** @description Opaque workspace ID. Requests that carry one only see analyses created in it. */
                "X-ChangeGuard-Workspace"?: string | null;
            };
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDetail"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Analysis not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Input exceeds a size limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Unsupported input format */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Malformed input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_analysis_api_v1_analyses__analysis_id__delete: {
        parameters: {
            query?: never;
            header?: {
                /** @description Opaque workspace ID. Requests that carry one only see analyses created in it. */
                "X-ChangeGuard-Workspace"?: string | null;
            };
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Analysis not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Input exceeds a size limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Unsupported input format */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Malformed input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    stream_events_api_v1_analyses__analysis_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
                /** @description Opaque workspace ID. Requests that carry one only see analyses created in it. */
                "X-ChangeGuard-Workspace"?: string | null;
            };
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent progress events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": unknown;
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Analysis not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Input exceeds a size limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Unsupported input format */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Malformed input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    export_analysis_api_v1_analyses__analysis_id__export_get: {
        parameters: {
            query?: {
                format?: "json" | "markdown" | "sarif";
            };
            header?: {
                /** @description Opaque workspace ID. Requests that carry one only see analyses created in it. */
                "X-ChangeGuard-Workspace"?: string | null;
            };
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/sarif+json": unknown;
                    "text/markdown": unknown;
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Analysis not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Input exceeds a size limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Unsupported input format */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Malformed input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    evaluation_api_v1_evaluation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    rules_api_v1_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleInfo"][];
                };
            };
        };
    };
    list_samples_api_v1_samples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleSummary"][];
                };
            };
        };
    };
    sample_detail_api_v1_samples__sample_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleDetail"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Analysis not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Input exceeds a size limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Unsupported input format */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Malformed input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    analyse_sample_api_v1_samples__sample_id__analyses_post: {
        parameters: {
            query?: {
                /** @description Run optional AI synthesis */
                ai?: boolean;
                /** @description Include the repository snapshot (full-context mode) */
                snapshot?: boolean;
                /** @description Include the sample's coverage report */
                coverage?: boolean;
            };
            header?: {
                /** @description Opaque workspace ID. Requests that carry one only see analyses created in it. */
                "X-ChangeGuard-Workspace"?: string | null;
            };
            path: {
                sample_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSummary"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Analysis not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Input exceeds a size limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Unsupported input format */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Malformed input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
