"""Built-in sample scenarios (clearly labelled synthetic data for demos).

Each sample directory contains ``sample.json`` (metadata and narrative),
``base/`` (the repository before the change), ``change.patch`` (generated by
``git diff`` via ``tools/make_patch.py``), and optionally a coverage report.
"""

from __future__ import annotations

import functools
import io
import json
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

DATA_DIR = Path(__file__).parent / "data"
_COVERAGE_NAMES = ("coverage.xml", "lcov.info", "coverage.json")


@dataclass(frozen=True, slots=True)
class Sample:
    id: str
    title: str
    tagline: str
    description: str
    language: str
    tags: tuple[str, ...]
    highlights: tuple[str, ...]
    directory: Path
    order: int = 100
    extra: dict[str, Any] = field(default_factory=dict)

    @property
    def patch_text(self) -> str:
        return (self.directory / "change.patch").read_text()

    @property
    def coverage_path(self) -> Path | None:
        for name in _COVERAGE_NAMES:
            candidate = self.directory / name
            if candidate.exists():
                return candidate
        return None

    def base_files(self) -> list[str]:
        base = self.directory / "base"
        return sorted(str(p.relative_to(base)) for p in base.rglob("*") if p.is_file())

    def archive(self) -> bytes:
        """The base snapshot as an in-memory zip (what a user would upload)."""
        buffer = io.BytesIO()
        base = self.directory / "base"
        with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            for path in sorted(base.rglob("*")):
                if path.is_file():
                    zf.write(path, str(path.relative_to(base)))
        return buffer.getvalue()


@functools.cache
def load_samples() -> dict[str, Sample]:
    samples: dict[str, Sample] = {}
    if not DATA_DIR.exists():
        return samples
    for directory in sorted(p for p in DATA_DIR.iterdir() if (p / "sample.json").exists()):
        meta = json.loads((directory / "sample.json").read_text())
        samples[meta["id"]] = Sample(
            id=meta["id"],
            title=meta["title"],
            tagline=meta["tagline"],
            description=meta["description"],
            language=meta["language"],
            tags=tuple(meta.get("tags", [])),
            highlights=tuple(meta.get("highlights", [])),
            directory=directory,
            order=int(meta.get("order", 100)),
            extra={
                k: v
                for k, v in meta.items()
                if k
                not in {
                    "id",
                    "title",
                    "tagline",
                    "description",
                    "language",
                    "tags",
                    "highlights",
                    "order",
                }
            },
        )
    return dict(sorted(samples.items(), key=lambda kv: (kv[1].order, kv[0])))


def get_sample(sample_id: str) -> Sample | None:
    return load_samples().get(sample_id)
