"""The web app ships data generated by the engine. Fail when it no longer matches the engine."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from changeguard import RULESET_VERSION
from changeguard.analysis.context import AnalysisOptions
from changeguard.analysis.pipeline import AnalysisPipeline
from changeguard.analysis.rules.catalog import all_rules
from changeguard.config import Settings
from changeguard.ingest.prepare import prepare_input
from changeguard.samples import get_sample

DATA = Path(__file__).resolve().parents[3] / "frontend" / "src" / "data"
HINT = (
    "the web app's data is stale: regenerate with `make data` (and `make eval` for evaluation.json)"
)

pytestmark = [
    pytest.mark.integration,
    pytest.mark.skipif(not DATA.exists(), reason="frontend data not present"),
]


def test_rule_catalogue_matches_the_engine() -> None:
    shipped = json.loads((DATA / "rules.json").read_text())
    assert shipped == json.loads(json.dumps(all_rules())), HINT


def test_recorded_sample_report_matches_a_fresh_run() -> None:
    shipped = json.loads((DATA / "sample-report.json").read_text())
    sample = get_sample("billing-refactor")
    assert sample is not None and sample.coverage_path is not None
    prepared = prepare_input(
        Settings(),
        patch=sample.patch_text,
        archive=sample.archive(),
        coverage=sample.coverage_path.read_bytes(),
    )
    report = AnalysisPipeline().run(
        prepared,
        analysis_id="freshness-check",
        created_at="2026-10-08T00:00:00Z",
        options=AnalysisOptions(title="freshness"),
    )
    assert shipped["ruleset_version"] == RULESET_VERSION, HINT
    assert [f["id"] for f in shipped["findings"]] == [f.id for f in report.findings], HINT
    assert [e["id"] for e in shipped["evidence"]] == [e.id for e in report.evidence], HINT


def test_evaluation_data_was_produced_by_this_ruleset() -> None:
    shipped = json.loads((DATA / "evaluation.json").read_text())
    assert shipped["manifest"]["ruleset_version"] == RULESET_VERSION, HINT
