import "server-only";

import evaluationJson from "@/data/evaluation.json";
import rulesJson from "@/data/rules.json";
import sampleReportAIJson from "@/data/sample-report-ai.json";
import sampleReportJson from "@/data/sample-report.json";
import sampleJson from "@/data/sample.json";

import type { Report, RuleInfo } from "./api/types";
import type { InstrumentData } from "@/components/landing/hero-instrument";

/** Real output of the engine on the billing sample (generated by backend/tools/export_frontend_data.py). */
export const sampleReport = sampleReportJson as unknown as Report;
export const sampleReportAI = sampleReportAIJson as unknown as Report;
export const rules = rulesJson as RuleInfo[];

/** Labelled metadata of the bundled synthetic sample. */
export const sampleMeta = sampleJson as {
  id: string;
  title: string;
  tagline: string;
  description: string;
  language: string;
  highlights: string[];
  synthetic: boolean;
  base_files: string[];
  coverage_filename: string | null;
};

/** The engine's own exports of the recorded sample report (written by export_frontend_data.py). */
export const sampleExports = {
  json: "/samples/billing-refactor/report.json",
  markdown: "/samples/billing-refactor/report.md",
  sarif: "/samples/billing-refactor/report.sarif",
};

export interface EvalCounts {
  tp: number;
  fp: number;
  fn: number;
  precision: number | null;
  recall: number | null;
  f1: number | null;
}

export interface EvalSystem {
  system: string;
  description: string;
  cases: number;
  labels: number;
  predictions: number;
  overall: EvalCounts;
  ci95: Record<"precision" | "recall" | "f1", [number | null, number | null]>;
  by_split: Record<string, EvalCounts>;
  ci95_by_split: Record<string, Record<"precision" | "recall" | "f1", [number | null, number | null]>>;
  by_category: Record<string, EvalCounts>;
  by_kind: Record<string, { tp?: number; fp?: number; acceptable?: number; precision: number | null }>;
  by_confidence: Record<string, { tp?: number; fp?: number; acceptable?: number; precision: number | null }>;
  negative_controls: { cases: number; cases_with_false_positive: number; false_positive_rate: number | null; false_positives_per_case: number | null };
  evidence: { findings_checked: number; unsupported_findings: number; unsupported_rate: number | null };
  severity_agreement: { exact: number | null; within_one_level: number | null };
  latency_ms: { mean: number | null; p95: number | null };
  ai: Record<string, unknown>;
}

export interface Evaluation {
  holdout_history: {
    description: string;
    runs: {
      split: string;
      cases: number;
      labels: number;
      negative_controls: number;
      ruleset: string;
      date: string;
      raw_output: string;
      systems: Record<string, { precision: number; recall: number; f1: number; negative_fp_rate: number }>;
      changes_after: string[];
    }[];
  } | null;
  manifest: {
    generated_at: string;
    changeguard_version: string;
    ruleset_version: string;
    git_sha: string | null;
    dataset_sha256: string;
    cases: number;
    splits: Record<string, number>;
    negative_controls: number;
    labels: number;
    bootstrap: { samples: number; seed: number; unit: string };
    matching: { rule: string };
    environment: Record<string, string | null>;
    ai: Record<string, unknown>;
  };
  systems: EvalSystem[];
  cases: { case: string; split: string; negative: boolean; matched: string[]; missed: string[]; false_positives: string[]; acceptable: number }[];
  misses: {
    case: string;
    title: string;
    split: string;
    description: string;
    label: string;
    category: string;
    file: string;
    lines: number[] | null;
    note: string;
    found_by: string[];
  }[];
  limitations: string[];
}

export const evaluation = evaluationJson as unknown as Evaluation;

export function systemByName(name: string): EvalSystem | undefined {
  return evaluation.systems.find((s) => s.system === name);
}

/** Slim view of the sample report for the landing-page figure (keeps the RSC payload small). */
export function instrumentData(): InstrumentData {
  const report = sampleReport;
  const file = report.files.find((f) => f.path.endsWith("pricing.py")) ?? report.files[0];
  const rows = file.hunks.flatMap((h) => h.lines);
  const pick = (needle: string, kind: "add" | "del") => rows.find((l) => l.kind === kind && l.content.includes(needle));
  const lines = [pick("if percent", "del"), pick("if percent", "add"), pick("def format_price", "del"), pick("def format_price", "add")].filter(
    (l): l is NonNullable<typeof l> => Boolean(l),
  );
  return {
    file: file.path,
    diff: lines.map((l) => ({ kind: l.kind, text: l.content.trim(), line: l.kind === "del" ? l.old ?? null : l.new ?? null })),
    stages: report.pipeline.filter((s) => s.status !== "skipped").map((s) => ({ label: s.label, ms: s.duration_ms })),
    findings: report.findings.slice(0, 4).map((f) => ({
      title: f.title,
      severity: f.severity,
      kind: f.kind,
      where: `${f.location.file}${f.location.start_line ? `:${f.location.start_line}` : ""}`,
    })),
    totalFindings: report.findings.length,
    totalMs: report.pipeline.reduce((sum, s) => sum + s.duration_ms, 0),
  };
}
